In [99]:
%run ./Day_03.ipynb


Hello
[1 3 5 7 9]
[[1 3]
 [2 4]]
[[5 7]
 [8 9]]


C:\Users\softl\AppData\Local\Temp\ipykernel_19584\2626738034.py:1: RuntimeWarning: divide by zero encountered in divide
  np.divide(a,b)
C:\Users\softl\AppData\Local\Temp\ipykernel_19584\3371653468.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.floor_divide(a,b)
C:\Users\softl\AppData\Local\Temp\ipykernel_19584\3052545775.py:2: RuntimeWarning: divide by zero encountered in remainder
  np.mod(a,b)
C:\Users\softl\AppData\Local\Temp\ipykernel_19584\1843698144.py:2: RuntimeWarning: divide by zero encountered in divmod
  np.divmod(a,b)
C:\Users\softl\AppData\Local\Temp\ipykernel_19584\4069035518.py:2: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  np.cross(a,b)


**DAY - 04 | Date : 21.01.26**


In [100]:
#head - displays top row (default n=5)
df.head(3)

Stu_Name  Roll  Marks
0   Aniket   111     95
1  Sourita   112     88
2   Trisha   113     76

In [101]:
df.head()

Stu_Name  Roll  Marks
0   Aniket   111     95
1  Sourita   112     88
2   Trisha   113     76
3   Simran   114     89

In [102]:
#tail- displays bottom row (default n=5)
df.tail(2)

Stu_Name  Roll  Marks
2   Trisha   113     76
3   Simran   114     89

In [103]:
#sample
df.sample()

Stu_Name  Roll  Marks
2   Trisha   113     76

In [104]:
df.sample(2)

Stu_Name  Roll  Marks
0   Aniket   111     95
2   Trisha   113     76

In [105]:
#set_index
df.set_index("Marks", inplace=True)
df

Stu_Name  Roll
Marks               
95      Aniket   111
88     Sourita   112
76      Trisha   113
89      Simran   114

In [106]:
# After correcting the rename operation in cell KwPY8jpoK1aa and re-running it,
# the column will be 'Stu_Name'. The DataFrame's index is now 'Marks'.
# If you intend to access 'Sourita', which has a 'Marks' index of 88:
# df.Stu_Name[88]

# If you intend to find the 'Stu_Name' for 'Roll' 112:
df[df['Roll'] == 112]['Stu_Name'].iloc[0]

'Sourita'

In [107]:
import numpy as np

In [108]:
d= pd.DataFrame({'Days':[1,2,3,4,5],
                 'Places':['Puri',np.nan,'Delhi','Mumbai','Chennai'],
                 'visitors':[100,200,300,400,500]})
d

Days   Places  visitors
0     1     Puri       100
1     2      NaN       200
2     3    Delhi       300
3     4   Mumbai       400
4     5  Chennai       500

In [109]:
#To check missing values
d.isnull().sum()


Days        0
Places      1
visitors    0
dtype: int64

In [110]:
#To check missing values
d.isnull()

Days  Places  visitors
0  False   False     False
1  False    True     False
2  False   False     False
3  False   False     False
4  False   False     False

In [111]:
#fillna - to fill missing values
d['Places'] = d['Places'].fillna('Goa')
d

Days   Places  visitors
0     1     Puri       100
1     2      Goa       200
2     3    Delhi       300
3     4   Mumbai       400
4     5  Chennai       500

In [112]:
#to check datatypes
d.dtypes

Days         int64
Places      object
visitors     int64
dtype: object

In [113]:
#info
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Days      5 non-null      int64 
 1   Places    5 non-null      object
 2   visitors  5 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes


In [114]:
d.shape

(5, 3)

In [115]:
d.ndim

2

In [116]:
d.Places.unique()

array(['Puri', 'Goa', 'Delhi', 'Mumbai', 'Chennai'], dtype=object)

In [117]:
d.visitors.mean()

np.float64(300.0)

In [118]:
d.visitors.max()

500

In [119]:
d.visitors.min()

100

In [120]:
#describe
d.describe()

Days    visitors
count  5.000000    5.000000
mean   3.000000  300.000000
std    1.581139  158.113883
min    1.000000  100.000000
25%    2.000000  200.000000
50%    3.000000  300.000000
75%    4.000000  400.000000
max    5.000000  500.000000

In [121]:
d.describe(include='all')

Days Places    visitors
count   5.000000      5    5.000000
unique       NaN      5         NaN
top          NaN   Puri         NaN
freq         NaN      1         NaN
mean    3.000000    NaN  300.000000
std     1.581139    NaN  158.113883
min     1.000000    NaN  100.000000
25%     2.000000    NaN  200.000000
50%     3.000000    NaN  300.000000
75%     4.000000    NaN  400.000000
max     5.000000    NaN  500.000000

In [122]:
d.describe(include='O')

Places
count       5
unique      5
top      Puri
freq        1

Iris Dataset


In [123]:
#import packagas
import pandas as pd
import numpy as np

In [124]:
#Reading a dataset
#csv- comma separated values
# The original file '/content/iris.data' was not found.
# We will load the Iris dataset from a public URL.
iris = pd.read_csv("D:\Data_Analytics_2026(Course)\Python\Dataset\iris\iris.data", header=None)
iris

0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [125]:
# The dataset loaded with header already has appropriate column names.
# If you still want to rename them for consistency with earlier attempts:
iris.columns = ['SL','SW','PL','PW','Flower Type']

# Ensure numerical columns are of numeric type, coercing errors to NaN
iris['SL'] = pd.to_numeric(iris['SL'], errors='coerce')
iris['SW'] = pd.to_numeric(iris['SW'], errors='coerce')
iris['PL'] = pd.to_numeric(iris['PL'], errors='coerce')
iris['PW'] = pd.to_numeric(iris['PW'], errors='coerce')

# Drop any rows where these conversions resulted in NaN values
iris.dropna(subset=['SL', 'SW', 'PL', 'PW'], inplace=True)

iris.info() # Add this to verify dtypes
iris

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   SL           150 non-null    float64
 1   SW           150 non-null    float64
 2   PL           150 non-null    float64
 3   PW           150 non-null    float64
 4   Flower Type  150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


SL   SW   PL   PW     Flower Type
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [126]:
iris.head(10)

SL   SW   PL   PW  Flower Type
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa
5  5.4  3.9  1.7  0.4  Iris-setosa
6  4.6  3.4  1.4  0.3  Iris-setosa
7  5.0  3.4  1.5  0.2  Iris-setosa
8  4.4  2.9  1.4  0.2  Iris-setosa
9  4.9  3.1  1.5  0.1  Iris-setosa

In [127]:
iris.head()

SL   SW   PL   PW  Flower Type
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [128]:
iris.tail()

SL   SW   PL   PW     Flower Type
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

In [129]:
iris.sample(5)

SL   SW   PL   PW      Flower Type
51   6.4  3.2  4.5  1.5  Iris-versicolor
55   5.7  2.8  4.5  1.3  Iris-versicolor
129  7.2  3.0  5.8  1.6   Iris-virginica
124  6.7  3.3  5.7  2.1   Iris-virginica
56   6.3  3.3  4.7  1.6  Iris-versicolor

In [130]:
iris.isnull().sum()

SL             0
SW             0
PL             0
PW             0
Flower Type    0
dtype: int64

In [131]:
iris.dtypes

SL             float64
SW             float64
PL             float64
PW             float64
Flower Type     object
dtype: object

In [132]:
iris.SL.dtypes

dtype('float64')

In [133]:
iris["Flower Type"].dtypes

dtype('O')

In [134]:
iris["SW"].dtypes

dtype('float64')

In [135]:
#info
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   SL           150 non-null    float64
 1   SW           150 non-null    float64
 2   PL           150 non-null    float64
 3   PW           150 non-null    float64
 4   Flower Type  150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [136]:
iris.SL.unique()

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.4, 4.8, 4.3, 5.8, 5.7, 5.2, 5.5,
       4.5, 5.3, 7. , 6.4, 6.9, 6.5, 6.3, 6.6, 5.9, 6. , 6.1, 5.6, 6.7,
       6.2, 6.8, 7.1, 7.6, 7.3, 7.2, 7.7, 7.4, 7.9])

In [137]:
iris["Flower Type"].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [138]:
for i in iris.columns:
    print(i,';','\n',iris[i].unique(),'\n')

SL ; 
 [5.1 4.9 4.7 4.6 5.  5.4 4.4 4.8 4.3 5.8 5.7 5.2 5.5 4.5 5.3 7.  6.4 6.9
 6.5 6.3 6.6 5.9 6.  6.1 5.6 6.7 6.2 6.8 7.1 7.6 7.3 7.2 7.7 7.4 7.9] 

SW ; 
 [3.5 3.  3.2 3.1 3.6 3.9 3.4 2.9 3.7 4.  4.4 3.8 3.3 4.1 4.2 2.3 2.8 2.4
 2.7 2.  2.2 2.5 2.6] 

PL ; 
 [1.4 1.3 1.5 1.7 1.6 1.1 1.2 1.  1.9 4.7 4.5 4.9 4.  4.6 3.3 3.9 3.5 4.2
 3.6 4.4 4.1 4.8 4.3 5.  3.8 3.7 5.1 3.  6.  5.9 5.6 5.8 6.6 6.3 6.1 5.3
 5.5 6.7 6.9 5.7 6.4 5.4 5.2] 

PW ; 
 [0.2 0.4 0.3 0.1 0.5 0.6 1.4 1.5 1.3 1.6 1.  1.1 1.8 1.2 1.7 2.5 1.9 2.1
 2.2 2.  2.4 2.3] 

Flower Type ; 
 ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica'] 



In [139]:
iris.describe(include='all')

SL          SW          PL          PW  Flower Type
count   150.000000  150.000000  150.000000  150.000000          150
unique         NaN         NaN         NaN         NaN            3
top            NaN         NaN         NaN         NaN  Iris-setosa
freq           NaN         NaN         NaN         NaN           50
mean      5.843333    3.054000    3.758667    1.198667          NaN
std       0.828066    0.433594    1.764420    0.763161          NaN
min       4.300000    2.000000    1.000000    0.100000          NaN
25%       5.100000    2.800000    1.600000    0.300000          NaN
50%       5.800000    3.000000    4.350000    1.300000          NaN
75%       6.400000    3.300000    5.100000    1.800000          NaN
max       7.900000    4.400000    6.900000    2.500000          NaN

In [140]:
iris.describe(include='O')

Flower Type
count           150
unique            3
top     Iris-setosa
freq             50

In [141]:
iris["Flower Type"].value_counts()

Flower Type
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [142]:
iris.SL.value_counts()

SL
5.0    10
5.1     9
6.3     9
5.7     8
6.7     8
5.8     7
5.5     7
6.4     7
4.9     6
5.4     6
6.1     6
6.0     6
5.6     6
4.8     5
6.5     5
6.2     4
7.7     4
6.9     4
4.6     4
5.2     4
5.9     3
4.4     3
7.2     3
6.8     3
6.6     2
4.7     2
7.6     1
7.4     1
7.3     1
7.0     1
7.1     1
5.3     1
4.3     1
4.5     1
7.9     1
Name: count, dtype: int64

In [143]:
#to drop a column
iris.drop('Flower Type', axis=1)
iris

SL   SW   PL   PW     Flower Type
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

Auto MPG


In [144]:
import pandas as pd
import numpy as np

In [145]:
auto = pd.read_csv(r"D:\Data_Analytics_2026(Course)\Python\Dataset\auto+mpg\Index")
auto

Index of auto-mpg
0                   02 Dec 1996      161 Index
1           07 Jul 1993    30286 auto-mpg.data
2  07 Jul 1993    32149 auto-mpg.data-original
3          07 Jul 1993     1660 auto-mpg.names

In [146]:
auto = pd.read_csv(r"d:/Data_Analytics_2026(Course)/Python/Dataset/auto+mpg/auto-mpg.data", header=None, sep='\s+') # Loaded from local file


In [147]:
auto.columns = ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model year', 'origin', 'car name']
auto.head()

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0      130.0  3504.0          12.0          70   
1  15.0          8         350.0      165.0  3693.0          11.5          70   
2  18.0          8         318.0      150.0  3436.0          11.0          70   
3  16.0          8         304.0      150.0  3433.0          12.0          70   
4  17.0          8         302.0      140.0  3449.0          10.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [148]:
#check missing values
auto.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [149]:
#check data types
auto.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight          float64
acceleration    float64
model year        int64
origin            int64
car name         object
dtype: object

In [150]:
#check unique values
for i in auto.columns:
    print(i,':','\n',auto[i].unique(),'\n')

mpg : 
 [18.  15.  16.  17.  14.  24.  22.  21.  27.  26.  25.  10.  11.   9.
 28.  19.  12.  13.  23.  30.  31.  35.  20.  29.  32.  33.  17.5 15.5
 14.5 22.5 24.5 18.5 29.5 26.5 16.5 31.5 36.  25.5 33.5 20.5 30.5 21.5
 43.1 36.1 32.8 39.4 19.9 19.4 20.2 19.2 25.1 20.6 20.8 18.6 18.1 17.7
 27.5 27.2 30.9 21.1 23.2 23.8 23.9 20.3 21.6 16.2 19.8 22.3 17.6 18.2
 16.9 31.9 34.1 35.7 27.4 25.4 34.2 34.5 31.8 37.3 28.4 28.8 26.8 41.5
 38.1 32.1 37.2 26.4 24.3 19.1 34.3 29.8 31.3 37.  32.2 46.6 27.9 40.8
 44.3 43.4 36.4 44.6 40.9 33.8 32.7 23.7 23.6 32.4 26.6 25.8 23.5 39.1
 39.  35.1 32.3 37.7 34.7 34.4 29.9 33.7 32.9 31.6 28.1 30.7 24.2 22.4
 34.  38.  44. ] 

cylinders : 
 [8 4 6 3 5] 

displacement : 
 [307.  350.  318.  304.  302.  429.  454.  440.  455.  390.  383.  340.
 400.  113.  198.  199.  200.   97.  110.  107.  104.  121.  360.  140.
  98.  232.  225.  250.  351.  258.  122.  116.   79.   88.   71.   72.
  91.   97.5  70.  120.   96.  108.  155.   68.  114.  156.   76.   83.
  