**DAY 01** : 17th Jan 2026

# 🌟NumPy - "Numerical Python"
<pre><b>Numpy  is a Python's library which is used to perform different mathematical operations on arrays.

Array is denoted with "[]". It is ordered (index position is fixed), mutable (items can be modified) and homogenous (similar datatypes) colection of items.</pre>


In [1]:
print("Hello")

Hello


In [2]:
#to import numpy
import numpy as np

In [3]:
#to check the version of numpy
np.__version__

'2.3.5'

# h1
## h2
### h3
#### h4
##### h5
###### h6
<pre> 🔴 Python is a programming Language
For installation '!pip install numpy' for numpy</pre>


In [4]:
#Creating 1D Array.
a=np.array([1,3,5,7,9])
print(a)
a

[1 3 5 7 9]


array([1, 3, 5, 7, 9])

In [5]:
type(a) #ndarray: n - dimentional array

numpy.ndarray

In [6]:
#dtype='<U32' - It defines that the characters and elements must be less that 32 bit max.
a=np.array([20,'tree',3.5,True])
a

array(['20', 'tree', '3.5', 'True'], dtype='<U32')

In [7]:
a=np.array(['cat','tree','dog','aeroplane','11','25'],dtype='<U3')
a

array(['cat', 'tre', 'dog', 'aer', '11', '25'], dtype='<U3')

In [8]:
a=np.array([20,3.5,55,True])
a

array([20. ,  3.5, 55. ,  1. ])

In [9]:
#Tuple to Array
t=np.array((10,20,30,50))
t

array([10, 20, 30, 50])

In [10]:
#Set to Array
s=np.array({1,1,1,1,8,8,8,4,4,4})
s

array({8, 1, 4}, dtype=object)

In [11]:
#Dict to Array
d=np.array({'a':1,'b':2,'c':3})
d

array({'a': 1, 'b': 2, 'c': 3}, dtype=object)

In [12]:
#Creating 2D-Array
b=np.array([[1,3,5],[2,4,6]])
b

array([[1, 3, 5],
       [2, 4, 6]])