In [4]:
%run ./Day_01.ipynb

Hello
[1 3 5 7 9]


**DAY 2 :** 19th Jan 2026

In [5]:
import numpy as np

In [6]:
#Creating 3D Array
b=np.array([[1,2,3,4],[5,6,7,8],[2,9,6,4]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 9, 6, 4]])

In [7]:
#Shape is (Row -3,Coloumn -4)
b.shape

(3, 4)

In [8]:
#Total No. of elements in an Array.
b.size

12

In [9]:
b.ndim

2

In [10]:
a=np.array([[[[[[[[[[[1]]]]]]]]]]])
a.ndim

11

In [11]:
a=np.array([1],ndmin=32)
a

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [12]:
#Range(Start, Stop,Step)
#arange
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [13]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [14]:
#zeroes
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.zeros((5,5),dtype='int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [17]:
np.zeros((5,5),dtype=dict)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=object)

In [18]:
np.zeros((5,5)).astype(int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [19]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
#full
np.full((5,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [21]:
np.full((5,5),'Sourita❤️')

array([['Sourita❤️', 'Sourita❤️', 'Sourita❤️', 'Sourita❤️', 'Sourita❤️'],
       ['Sourita❤️', 'Sourita❤️', 'Sourita❤️', 'Sourita❤️', 'Sourita❤️'],
       ['Sourita❤️', 'Sourita❤️', 'Sourita❤️', 'Sourita❤️', 'Sourita❤️'],
       ['Sourita❤️', 'Sourita❤️', 'Sourita❤️', 'Sourita❤️', 'Sourita❤️'],
       ['Sourita❤️', 'Sourita❤️', 'Sourita❤️', 'Sourita❤️', 'Sourita❤️']],
      dtype='<U9')

In [22]:
#eye-identity matrix
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [23]:
#Linspace - equally distributed numbers
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [24]:
#Random Numbers
np.random.rand()

0.945234427956291

In [25]:
np.random.rand(5)

array([0.55268542, 0.74603813, 0.76176717, 0.41935778, 0.59634115])

In [26]:
np.random.randint(1,200000000)

182150626

In [27]:
np.random.rand(3,4,5)

array([[[0.61072173, 0.4710768 , 0.18979955, 0.55188643, 0.11756609],
        [0.54713546, 0.03119901, 0.60655082, 0.94591752, 0.37246265],
        [0.53570022, 0.54081652, 0.42698418, 0.86569286, 0.65641924],
        [0.33977803, 0.48896211, 0.2210432 , 0.43168896, 0.86396281]],

       [[0.81983014, 0.28784947, 0.46381932, 0.30738142, 0.42662315],
        [0.18539328, 0.27485007, 0.41586409, 0.93139127, 0.74483287],
        [0.14335809, 0.70329508, 0.55530444, 0.91619211, 0.62079026],
        [0.28284297, 0.72716442, 0.45185189, 0.62853452, 0.23802356]],

       [[0.98454734, 0.32902621, 0.51439034, 0.95786589, 0.50411576],
        [0.6134659 , 0.20053366, 0.88109439, 0.16604034, 0.89847245],
        [0.92114761, 0.06607867, 0.11687201, 0.49287254, 0.61441897],
        [0.01077821, 0.16985043, 0.17435092, 0.35533074, 0.71282953]]])

In [28]:
np.random.randint(1,20,(4,5))

array([[16, 14, 16, 15,  3],
       [13,  8,  3, 17,  2],
       [ 1,  9,  9, 16,  8],
       [12, 12,  6,  6,  1]], dtype=int32)

🌟 **Mathematical Operations.**

In [29]:
np.random.rand(1,20).astype(str)

array([['0.06619491200089311', '0.13281090753544833',
        '0.5425458229907617', '0.9086715613893871', '0.5535034699187633',
        '0.7225153747170916', '0.4988801463467275', '0.8903558286505131',
        '0.8119562280391014', '0.2727409031706406', '0.2766955300655555',
        '0.39572557233022587', '0.2664137249027967',
        '0.1418852341277853', '0.3788597326726657',
        '0.08712586200133121', '0.7556902462938142',
        '0.16932693310639446', '0.9489691020271515',
        '0.9550476572209028']], dtype='<U32')

In [30]:
a=np.array([23,57,75,82,35])
b=np.array([4,6,8,9,0])
a+b

array([27, 63, 83, 91, 35])

In [31]:
np.add(a,b)

array([27, 63, 83, 91, 35])

In [32]:
np.subtract(a,b)

array([19, 51, 67, 73, 35])

In [33]:
np.multiply(a,b)

array([ 92, 342, 600, 738,   0])

In [34]:
np.divide(a,b)

C:\Users\softl\AppData\Local\Temp\ipykernel_1080\2626738034.py:1: RuntimeWarning: divide by zero encountered in divide
  np.divide(a,b)


array([5.75      , 9.5       , 9.375     , 9.11111111,        inf])

In [35]:
#floor divide
np.floor_divide(a,b)

C:\Users\softl\AppData\Local\Temp\ipykernel_1080\3371653468.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.floor_divide(a,b)


array([5, 9, 9, 9, 0])

In [36]:
#MOD-MODULO
np.mod(a,b)

C:\Users\softl\AppData\Local\Temp\ipykernel_1080\3052545775.py:2: RuntimeWarning: divide by zero encountered in remainder
  np.mod(a,b)


array([3, 3, 3, 1, 0])

In [37]:
#divmod
np.divmod(a,b)

C:\Users\softl\AppData\Local\Temp\ipykernel_1080\1843698144.py:2: RuntimeWarning: divide by zero encountered in divmod
  np.divmod(a,b)


(array([5, 9, 9, 9, 0]), array([3, 3, 3, 1, 0]))

In [38]:
#log
np.log(a)

array([3.13549422, 4.04305127, 4.31748811, 4.40671925, 3.55534806])

In [39]:
np.log10(a)

array([1.36172784, 1.75587486, 1.87506126, 1.91381385, 1.54406804])

In [40]:
np.sqrt(a)

array([4.79583152, 7.54983444, 8.66025404, 9.05538514, 5.91607978])

In [41]:
#cbrt- Cube Root
np.cbrt(27)

np.float64(3.0)

In [42]:
np.cbrt(a)

array([2.84386698, 3.84850113, 4.21716333, 4.34448149, 3.27106631])

In [43]:
#power
np.power(2,4)

np.int64(16)

In [44]:
np.sin(90)

np.float64(0.8939966636005579)

In [45]:
np.sin(90*(np.pi/180)) #in degrees

np.float64(1.0)

In [46]:
np.sin(a)

array([-0.8462204 ,  0.43616476, -0.38778164,  0.31322878, -0.42818267])

In [47]:
np.tan(a)

array([ 1.58815308,  0.48469923, -0.42070095,  0.32982641,  0.47381472])

In [48]:
#cot
1/np.tan(a)

array([ 0.62966222,  2.06313513, -2.37698536,  3.03189793,  2.11052962])

Statiscal Function

In [49]:
#max
np.max(a)

np.int64(82)

In [50]:
#argamax
np.argmax(a)

np.int64(3)

In [51]:
#sort
np.sort(a)


array([23, 35, 57, 75, 82])

In [52]:
#argsort
np.argsort(a)


array([0, 4, 1, 2, 3])

In [53]:
#flip
np.flip(a)

array([35, 82, 75, 57, 23])

In [54]:
#mean-overage
np.mean(a)

np.float64(54.4)

In [55]:
np.median(a)

np.float64(57.0)

In [56]:
#std - Standard Deviation
np.std(a)

np.float64(22.60619384151167)

In [57]:
#var - Variance
np.var(a)

np.float64(511.0400000000001)

In [58]:
#cumsum
np.cumsum(a)

array([ 23,  80, 155, 237, 272])

In [59]:
#cumprod - Cumulative Product
np.cumprod(a)

array([       23,      1311,     98325,   8062650, 282192750])

In [60]:
#round off numbers
#round
np.round(a)

array([23, 57, 75, 82, 35])

In [61]:
#ceil
np.ceil(25.3)

np.float64(26.0)

In [62]:
#trunc
np.trunc(25.7)

np.float64(25.0)

In [63]:
#repeat
a = np.array([1,2,3])
np.repeat(a,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [64]:
#tile
a= np.array([1,2,3])
np.tile(a,4)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [65]:
#where
a= np.array([1,2,4,3,4,4,5,4,6,4])
np.where(a==4)

(array([2, 4, 5, 7, 9]),)

Vector Maths

In [66]:
a = np.array([[1,3],[2,4]])
b = np.array([[5,7],[8,9]])
print (a)
print (b)


[[1 3]
 [2 4]]
[[5 7]
 [8 9]]


In [67]:
#cross
np.cross(a,b)

C:\Users\softl\AppData\Local\Temp\ipykernel_1080\4069035518.py:2: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  np.cross(a,b)


array([ -8, -14])

In [68]:
np.dot(a,b)

array([[29, 34],
       [42, 50]])

In [69]:
#shortcut of dot product
a@b

array([[29, 34],
       [42, 50]])

In [70]:
a.T

array([[1, 2],
       [3, 4]])

In [71]:
import numpy as np
#Indexing and slicing in 1D Array
a=np.array([34,89,55,21,35])
a

array([34, 89, 55, 21, 35])

In [72]:
a[2]

np.int64(55)

In [73]:
#Slicing
a[0:5:2]

array([34, 55, 35])

In [74]:
#Indexing and Slicing in 2D Array
b=np.random.randint(1,20,(5,5))
b

array([[10, 16,  7,  9, 12],
       [18, 14, 16,  8, 11],
       [13, 13,  6, 18,  3],
       [13,  3, 13,  9,  5],
       [19, 14,  6, 10,  4]], dtype=int32)

In [75]:
#Indexing
#Syntax - var[row_index, column_index]
b[2,3]

np.int32(18)

In [76]:
b[1:4:1,1:4:1]

array([[14, 16,  8],
       [13,  6, 18],
       [ 3, 13,  9]], dtype=int32)

In [77]:
#All Rows and even columns (0,2,4)
b[:,0:4+1:2]

array([[10,  7, 12],
       [18, 16, 11],
       [13,  6,  3],
       [13, 13,  5],
       [19,  6,  4]], dtype=int32)

In [78]:
b[0:5:1,0:5:1]

array([[10, 16,  7,  9, 12],
       [18, 14, 16,  8, 11],
       [13, 13,  6, 18,  3],
       [13,  3, 13,  9,  5],
       [19, 14,  6, 10,  4]], dtype=int32)

In [79]:
b[0:5:2,0:5:2]

array([[10,  7, 12],
       [13,  6,  3],
       [19,  6,  4]], dtype=int32)

In [80]:
#Concatination - joining matrix
a=np.random.randint(1,10,(2,2))
a

array([[1, 1],
       [9, 2]], dtype=int32)

In [81]:

b=np.random.randint(1,20,(2,4))
b

array([[ 8, 19,  3, 12],
       [ 1,  8,  1, 17]], dtype=int32)

In [82]:
c=np.random.randint(1,20,(4,4))
c

array([[19,  5,  2, 10],
       [12,  8, 12, 10],
       [18, 15,  1, 11],
       [ 3,  8, 16,  2]], dtype=int32)

In [83]:
#Coloumn wise(axis=0) (by default)
np.concatenate((a,b),axis=1)

array([[ 1,  1,  8, 19,  3, 12],
       [ 9,  2,  1,  8,  1, 17]], dtype=int32)

In [84]:
#Row Wise(Axis =0) (by default)
np.concatenate((b,c),axis=0)

array([[ 8, 19,  3, 12],
       [ 1,  8,  1, 17],
       [19,  5,  2, 10],
       [12,  8, 12, 10],
       [18, 15,  1, 11],
       [ 3,  8, 16,  2]], dtype=int32)

In [85]:
#Stack - joining matrix
#hstack- Horizontal Stack
np.hstack((a,b))

array([[ 1,  1,  8, 19,  3, 12],
       [ 9,  2,  1,  8,  1, 17]], dtype=int32)

In [86]:
#Stack
a=np.array([1,2,3])
b=np.array([4,5,6])
np.stack((a,b),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [87]:
np.stack((a,b),axis=0)

array([[1, 2, 3],
       [4, 5, 6]])