In [1]:
%run ./Day_02.ipynb

Hello
[1 3 5 7 9]
[[1 3]
 [2 4]]
[[5 7]
 [8 9]]


C:\Users\softl\AppData\Local\Temp\ipykernel_12628\2626738034.py:1: RuntimeWarning: divide by zero encountered in divide
  np.divide(a,b)
C:\Users\softl\AppData\Local\Temp\ipykernel_12628\3371653468.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.floor_divide(a,b)
C:\Users\softl\AppData\Local\Temp\ipykernel_12628\3052545775.py:2: RuntimeWarning: divide by zero encountered in remainder
  np.mod(a,b)
C:\Users\softl\AppData\Local\Temp\ipykernel_12628\1843698144.py:2: RuntimeWarning: divide by zero encountered in divmod
  np.divmod(a,b)
C:\Users\softl\AppData\Local\Temp\ipykernel_12628\4069035518.py:2: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  np.cross(a,b)


DAY : 03 Date : 20th Jan 2026

Pandas is a pythons's library which is use to analyze and manipulate the data. It is also use to read and create datasets.

Panda is of two types:
---> Series(Single Column)
---> DataFrame(Multiple Coloumns)

In [2]:
import pandas as pd
#Creating series
s=pd.Series((10,20))
s

0    10
1    20
dtype: int64

In [3]:
type(s)

pandas.core.series.Series

In [4]:
s=pd.Series(['a','b','c','d','e'],index=[10,20,30,40,50])
s

10    a
20    b
30    c
40    d
50    e
dtype: object

In [5]:
#Slicing
s[1::2]

20    b
40    d
dtype: object

In [6]:
s[::-1]

50    e
40    d
30    c
20    b
10    a
dtype: object

In [7]:
s=pd.Series(['a','b','c','d','e'],index=np.arange(5,10))
s

5    a
6    b
7    c
8    d
9    e
dtype: object

In [8]:
#Tuple to Series
t=pd.Series((100,200,300,400,500))
t

0    100
1    200
2    300
3    400
4    500
dtype: int64

In [9]:
#indexing
t[2]

np.int64(300)

In [10]:
t[::-1]

4    500
3    400
2    300
1    200
0    100
dtype: int64

In [11]:
#Set to Series
s=pd.Series(list({35,35,35,10,10,25}))
s

0    25
1    10
2    35
dtype: int64

In [12]:
#Dictionary to series
d=pd.Series({'a':10,'b':20,'c':30})
d

a    10
b    20
c    30
dtype: int64

In [13]:
import pandas as pd

In [14]:
#Creation of DataFrame
d = {'Name':['Aniket','Sourita','Trisha','Simran'],
'Roll':[111,112,113,114],
'Marks':[95,88,76,89]}
d

{'Name': ['Aniket', 'Sourita', 'Trisha', 'Simran'],
 'Roll': [111, 112, 113, 114],
 'Marks': [95, 88, 76, 89]}

In [15]:
df = pd.DataFrame(d)
df

Name  Roll  Marks
0   Aniket   111     95
1  Sourita   112     88
2   Trisha   113     76
3   Simran   114     89

pandas.core.frame.DataFrame

In [16]:
#indexing
df.Name[2]

'Trisha'

In [17]:
df.Marks[3]

np.int64(89)

In [18]:
#slicing
#iloc - integer location(used for slicing)
df.iloc[::, ::]

Name  Roll  Marks
0   Aniket   111     95
1  Sourita   112     88
2   Trisha   113     76
3   Simran   114     89

In [19]:
#Reverse
df.iloc[::-1, ::-1]

Marks  Roll     Name
3     89   114   Simran
2     76   113   Trisha
1     88   112  Sourita
0     95   111   Aniket

In [20]:
df=df.rename(columns={'Name':'Stu_Name'})
df

Stu_Name  Roll  Marks
0   Aniket   111     95
1  Sourita   112     88
2   Trisha   113     76
3   Simran   114     89